version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: elramy_db
      MYSQL_USER: elramy
      MYSQL_PASSWORD: elramy_pwd
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - ntwrk
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: elramy
      RABBITMQ_DEFAULT_PASS: elramy_pwd
    ports:
      - "${RBTMQ_MGNT_PORT}:15672"
      - "${RBTMQ_PORT}:5672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    networks:
      - ntwrk
networks:
  ntwrk:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  rabbitdata:
    driver: "local"
